MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  PDNET_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: True
  PDNET:
    PRED_HEAD:
      DYNAMIC_POINT_PRED_CHANNELS: 34
      DYNAMIC_POINT_PRED_SPLITS: [4, 4, 18, 8]
      REG_MAP_OUT_CHANNELS: 4
      BOUND_POINT_NUM: 4
      CLS_MAP_OUT_CHANNELS: 720 # 9x(80)
      SEMANTIC_POINT_NUM: 9
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 16
  WARMUP_METHOD: "linear"
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 15000
  TEST_PERIOD: 15000
OUTPUT_DIR: work_dirs/pdnet/pdnet_R_50_FPN_2x/